from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('base/', views.base_view, name='base'),
    path('users/', views.user_list, name='user_list'),
    path('users/add/', views.add_user, name='add_user'),
    path('users/edit/<int:user_id>/', views.edit_user, name='edit_user'),
    path('users/delete/<int:user_id>/', views.delete_user, name='delete_user'),
    path('inventory/', views.inventory_list, name='inventory_list'),
    path('inventory/add/', views.add_inventory, name='add_inventory'),
    path('inventory/edit/<int:pk>/', views.inventory_edit, name='inventory_edit'),
    path('inventory/delete/<int:pk>/', views.inventory_delete, name='inventory_delete'),
    path('barang_terpakai/', views.barang_terpakai, name='barang_terpakai'),
    path('barang_terpakai/barang_edit/<int:pk>/', views.barang_edit, name='barang_edit'),
    path('barang_terpakai/barang_delete/<int:pk>/', views.barang_delete, name='barang_delete'),
    path('persediaan_barang/', views.persediaan_barang, name='persediaan_barang'),
    path('rooms/', views.room_list, name='room_list'),
    path('rooms/add/', views.add_room, name='add_room'),
    path('rooms/edit/<int:pk>/', views.edit_room, name='edit_room'),
    path('rooms/delete/<int:pk>/', views.delete_room, name='delete_room'),
    path('room_types/', views.room_type_list, name='room_type_list'),
    path('room_types/add/', views.add_room_type, name='add_room_type'),
    path('room_types/edit/<int:pk>/', views.edit_room_type, name='edit_room_type'),
    path('room_types/delete/<int:pk>/', views.delete_room_type, name='delete_room_type'),
    path('halls/', views.hall_list, name='hall_list'),
    path('halls/add/', views.add_hall, name='add_hall'),
    path('halls/edit/<int:pk>/', views.edit_hall, name='edit_hall'),
    path('halls/delete/<int:pk>/', views.delete_hall, name='delete_hall'),
    path('layanan/', views.layanan_list, name='layanan_list'),
    path('layanan/add/', views.add_layanan, name='add_layanan'),
    path('layanan/edit/<int:pk>/', views.edit_layanan, name='edit_layanan'),
    path('layanan/delete/<int:pk>/', views.delete_layanan, name='delete_layanan'),
    path('kategori-layanan/', views.kategori_layanan_list, name='kategori_layanan_list'),
    path('kategori-layanan/add/', views.add_kategori_layanan, name='add_kategori_layanan'),
    path('kategori-layanan/edit/<int:pk>/', views.edit_kategori_layanan, name='edit_kategori_layanan'),
    path('kategori-layanan/delete/<int:pk>/', views.delete_kategori_layanan, name='delete_kategori_layanan'),
    path('tamu/', views.tamu_list, name='tamu_list'),  # Daftar tamu
    path('tamu/add/', views.add_tamu, name='add_tamu'),  # Tambah tamu
    path('tamu/edit/<int:pk>/', views.edit_tamu, name='edit_tamu'),  # Edit tamu
    path('tamu/delete/<int:pk>/', views.delete_tamu, name='delete_tamu'),  # Hapus tamu
    path('check-in/', views.check_in_view, name='check_in'), 
    path('check-out/', views.check_out_view, name='check_out'),
    path('tamu-in-house/', views.tamu_in_house_view, name='tamu_in_house'),
    path('edit-tamu-in-house/<int:id>/', views.edit_tamu_in_house_view, name='edit_tamu_in_house'),
    path('room-service/tambah/', views.tambah_room_service, name='tambah_room_service'),
    path('room-service/success/', views.room_service_success, name='room_service_success'),  # URL setelah submit sukses
    path('cleaning/', views.cleaning_list_view, name='cleaning_list'),
    path('cleaning/<str:room_or_hall>/<int:id>/', views.mark_cleaned_view, name='mark_cleaned'),
    path('cleaning/export/', views.export_cleaning_log, name='export_cleaning_log'),
    path('cleaning/history/', views.cleaning_history_view, name='cleaning_history'),
    path('room-reports/', views.room_report_view, name='room_report_view'),
    path('export/reports/rooms/', views.export_room_report, name='export_room_report'),
    path('checkins/', views.checkin_report_view, name='checkin_report_view'),
    path('export/reports/checkins/', views.export_checkin_report, name='export_checkin_report'),
    path('checkouts/', views.checkout_report_view, name='checkout_report_view'),
    path('export/reports/checkouts/', views.export_checkout_report, name='export_checkout_report'),
    path('hall-reports/', views.hall_report_view, name='hall_report_view'),
    path('export/reports/halls/', views.export_hall_report, name='export_hall_report'),
    path('cleaning-logs/', views.cleaning_log_report_view, name='cleaning_log_report_view'),
    path('export/reports/cleaning-logs/', views.export_cleaning_log_report, name='export_cleaning_log_report'),
    
]