# Generated by Django 5.0 on 2024-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembelian', models.DateField()),
                ('no_po_nota', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_supplier', models.CharField(default='Unknown', max_length=200)),
                ('nama_barang', models.CharField(default='Unknown', max_length=200)),
                ('satuan', models.CharField(choices=[('item', 'Item'), ('pcs', 'Pcs'), ('box', 'Box'), ('kg', 'Kg')], default='pcs', max_length=10)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('stok_awal', models.PositiveIntegerField()),
                ('stok_tersedia', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
