# Generated by Django 5.0 on 2024-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
