# Generated by Django 5.0 on 2024-09-20 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hall_tipe_aula'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satuan', models.CharField(choices=[('satuan', 'Per Satuan'), ('porsi', 'Per Porsi'), ('pcs', 'Per Pcs'), ('pitcher', 'Per Pitcher')], max_length=10)),
                ('kategori_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.kategorilayanan')),
            ],
        ),
    ]
