# Generated by Django 5.0 on 2024-09-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_kategorilayanan_layanan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('warga_negara', models.CharField(max_length=50)),
                ('no_identitas', models.CharField(max_length=50, unique=True)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
