# Generated by Django 5.0 on 2024-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_status_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='room_or_hall',
            new_name='rooms',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='num_adults',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='num_children',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='vat',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
