# Generated by Django 5.0 on 2024-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_room_or_hall_checkin_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='guest_gender',
            field=models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], default='Tamu Tambahan', max_length=1),
            preserve_default=False,
        ),
    ]
