# Generated by Django 5.0 on 2024-09-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_checkin_guest_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='hall',
            new_name='aula',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='guest_gender',
            new_name='jenis_kelamin',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='num_adults',
            new_name='jumlah_anak',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='num_children',
            new_name='jumlah_dewasa',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='rooms',
            new_name='kamar',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='guest_name',
            new_name='nama_tamu',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='check_in_date',
            new_name='tanggal_check_in',
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='check_out_date',
            new_name='tanggal_check_out',
        ),
    ]
