# Generated by Django 5.0 on 2024-09-27 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='tanggal_check_out',
        ),
        migrations.AddField(
            model_name='checkout',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hall'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='kamar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tanggal_checkout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
