# Generated by Django 5.0 on 2024-09-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_checkout_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.checkin'),
        ),
    ]
