# Generated by Django 5.0 on 2024-09-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_checkout_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='checkin',
            new_name='check_in',
        ),
    ]
