# Generated by Django 5.0 on 2024-09-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_rename_checkin_checkout_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='tamu_checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.tamu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
