# Generated by Django 5.0 on 2024-10-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_remove_checkout_tamu_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='ppn',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
