# Generated by Django 5.0 on 2024-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_checkout_ppn_alter_checkin_total_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='sisa_pembayaran',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status_pembayaran',
            field=models.CharField(default='Belum Lunas', max_length=20),
        ),
    ]
