# Generated by Django 5.0 on 2024-10-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_checkin_status_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='tipe_aula',
            new_name='status',
        ),
    ]
