# Generated by Django 5.0 on 2024-10-29 13:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_rename_tipe_aula_hall_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_layanan', models.TextField(blank=True)),
                ('harga_layanan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tanggal_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.checkin')),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.layanan')),
            ],
        ),
    ]
