# Generated by Django 5.0 on 2024-11-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_cleaninglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
