# Generated by Django 5.0 on 2024-11-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0026_cleaninglog_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tidak Tersedia', 'Tidak Tersedia'), ('maintenance', 'Dalam Perawatan')], default='Tersedia', max_length=20),
        ),
    ]
