# Generated by Django 5.2.1 on 2025-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='satuan',
            field=models.CharField(choices=[('satuan', 'Per Satuan'), ('porsi', 'Per Porsi'), ('pcs', 'Per Pcs'), ('pitcher', 'Per Pitcher'), ('trip', 'Per Trip'), ('jam', 'Per Jam'), ('km', 'Per KM'), ('hari', 'Per Hari')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tamu',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
