# Generated by Django 5.2.1 on 2025-07-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0029_alter_layanan_satuan_alter_tamu_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanTamu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan', to='hotel.checkin')),
            ],
        ),
    ]
