# Generated by Django 5.2.4 on 2025-07-29 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_checkin_diskon'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='diskon_persen',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diskon dalam persen (0–100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='diskon',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diskon manual dalam rupiah (abaikan jika pakai %)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
