# Generated by Django 5.2.4 on 2025-07-29 22:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_checkin_diskon_persen_alter_checkin_diskon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='diskon',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='diskon_persen',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Diskon dalam persen (0–100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
