# Generated by Django 5.2.4 on 2026-03-01 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0036_recreate_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nama_tamu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.tamu'),
        ),
    ]
