# Generated by Django 5.2.4 on 2026-03-01 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_alter_booking_nama_tamu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nama_tamu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.tamu'),
            preserve_default=False,
        ),
    ]
