# Generated by Django 5.2.4 on 2026-03-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_alter_booking_nama_tamu'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nama_pemesan',
            field=models.CharField(default='Pemesan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='no_hp_pemesan',
            field=models.CharField(default='000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nama_tamu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.tamu'),
        ),
    ]
